export const SET_STANDARD_WIDGET = 'SET_STANDARD_WIDGET';

export const ADD_CUSTOM_WIDGET = 'ADD_CUSTOM_WIDGET';
export const UPDATE_WIDGET_DATA = 'UPDATE_WIDGET_DATA';
export const SET_WIDGET_DATA = 'SET_WIDGET_DATA';
