export const SET_STORAGE_STATUS = 'SET_STORAGE_STATUS';
export const SET_DEFAULT_DATA = 'SET_DEFAULT_DATA';
export const SET_PROFILE_DATA = 'SET_PROFILE_DATA';

export const START_FETCH_QUOTES = 'START_FETCH_QUOTES';
export const SUCCESS_FETCH_QUOTE = 'SUCCESS_FETCH_QUOTE';
export const ERROR_FETCH_QUOTES = 'ERROR_FETCH_QUOTES';

export const START_FETCH_COLLECTION = 'START_FETCH_COLLECTION';
export const SUCCESS_FETCH_COLLECTION = 'SUCCESS_FETCH_COLLECTION';
export const ERROR_FETCH_COLLECTION = 'ERROR_FETCH_COLLECTION';

export const START_PAST_QUOTES = 'START_PAST_QUOTES';
export const SUCCESS_PAST_QUOTES = 'SUCCESS_PAST_QUOTES';
export const ERROR_PAST_QUOTES = 'ERROR_PAST_QUOTES';

export const START_LIKE_QUOTE = 'START_LIKE_QUOTE';
export const SUCCESS_LIKE_QUOTE = 'SUCCESS_LIKE_QUOTE';
export const ERROR_LIKE_QUOTE = 'ERROR_LIKE_QUOTE';

export const SET_MODAL_PREMIUM_VISIBILITY = 'SET_MODAL_PREMIUM_VISIBILITY';

export const SET_APP_VERSION = 'SET_APP_VERSION';
export const SET_MODAL_FIRST_PREMIUM = 'SET_MODAL_FIRST_PREMIUM';

export const SET_END_REACH_QUOTE = 'SET_END_REACH_QUOTE';
export const SET_LIST_QUOTE_REF = 'SET_LIST_QUOTE_REF';
export const CHANGE_ASK_RATING_PARAMETER = 'CHANGE_ASK_RATING_PARAMETER';

export const SET_LIKE_STATUS = 'SET_LIKE_STATUS';
export const SET_REGISTER_STEP = 'SET_REGISTER_STEP';

export const SHOW_LOADING_MODAL = 'SHOW_LOADING_MODAL';
export const HIDE_LOADING_MODAL = 'HIDE_LOADING_MODAL';
export const CHANGE_COUNTER_LOADING_MODAL = 'CHANGE_COUNTER_LOADING_MODAL';

export const SET_TODAY_ADS_LIMIT = 'SET_TODAY_ADS_LIMIT';
export const RESET_TODAY_ADS_LIMIT = 'RESET_TODAY_ADS_LIMIT';

export const SET_NEW_QUOTE_DATA = 'SET_NEW_QUOTE_DATA';
export const SET_ANIMATION_SLIDE_DATA = 'SET_ANIMATION_SLIDE_DATA';
export const SET_INITIAL_FINISH_LOADER = 'SET_INITIAL_FINISH_LOADER';

export const SET_PAYWALL_NOTIFICATION = 'SET_PAYWALL_NOTIFICATION';
export const SET_ANIMATION_COUNTER = 'SET_ANIMATION_COUNTER';
export const SET_USER_THEMES = 'SET_USER_THEMES';
